# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GreedoLayoutExample' do
  pod 'GreedoLayout', :git => 'https://github.com/500px/greedo-layout-for-ios.git'
end

target 'GreedoLayoutExampleTests' do
  pod 'GreedoLayout', :git => 'https://github.com/500px/greedo-layout-for-ios.git'
end
